traditional <- read.csv(file.choose(), header = TRUE)
smartContract <- read.csv(file.choose(), header = TRUE)
setwd("Set your path")
png(file = "Avg_Assignment.png")
boxplot(traditional$BW.Avg.Assignment,smartContract$Avg.Assignment,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_blank_lines.png")
boxplot(traditional$BW.Avg.blank.lines,smartContract$Avg.blank.lines,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_commas.png")
boxplot(traditional$BW.Avg.commas,smartContract$Avg.commas,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_comments.png")
boxplot(traditional$BW.Avg.comments,smartContract$Avg.comments,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_comparisons.png")
boxplot(traditional$BW.Avg.comparisons,smartContract$Avg.comparisons,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )  
dev.off()
png(file = "Avg_Identifiers_Length.png")
boxplot(traditional$BW.Avg.Identifiers.Length,smartContract$Avg.Identifiers.Length,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" ) 
dev.off()
png(file = "Avg_conditionals.png")
boxplot(traditional$BW.Avg.conditionals,smartContract$Avg.conditionals,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" ) 
dev.off()
png(file = "Avg_indentation.png")
boxplot(traditional$BW.Avg.indentation.length,smartContract$Avg.indentation.length,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" ) 
dev.off()
png(file = "Avg_keywords.png")
boxplot(traditional$BW.Avg.keywords,smartContract$Avg.keywords,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" ) 
dev.off()
png(file = "Avg_line_length.png")
boxplot(traditional$BW.Avg.line.length,smartContract$Avg.line.length,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" ) 
dev.off()
png(file = "Avg_loops.png")  
boxplot(traditional$BW.Avg.loops,smartContract$Avg.loops,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_number_of_identifiers.png")
boxplot(traditional$BW.Avg.number.of.identifiers,smartContract$Avg.number.of.identifiers,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_numbers.png")
boxplot(traditional$BW.Avg.numbers,smartContract$Avg.numbers,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_operators.png")
boxplot(traditional$BW.Avg.operators,smartContract$Avg.operators,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()          
png(file = "Avg_parenthesis.png")		  
boxplot(traditional$BW.Avg.parenthesis,smartContract$Avg.parenthesis,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_periods.png")
boxplot(traditional$BW.Avg.periods,smartContract$Avg.periods,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Avg_spaces.png")
boxplot(traditional$BW.Avg.spaces,smartContract$Avg.spaces,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_Identifiers_Length.png")
boxplot(traditional$BW.Max.Identifiers.Length,smartContract$Max.Identifiers.Length,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_indentation.png")
boxplot(traditional$BW.Max.indentation,smartContract$Max.indentation,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_keywords.png")
boxplot(traditional$BW.Max.keywords,smartContract$Max.keywords,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_line_length.png")
boxplot(traditional$BW.Max.line.length,smartContract$Max.line.length,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_number_of_identifiers.png")
boxplot(traditional$BW.Max.number.of.identifiers,smartContract$Max.number.of.identifiers,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_numbers.png")
boxplot(traditional$BW.Max.numbers,smartContract$Max.numbers,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_char.png")
boxplot(traditional$BW.Max.char,smartContract$Max.char,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()
png(file = "Max_words.png")
boxplot(traditional$BW.Max.words,smartContract$Max.words,outline=FALSE,names = c("Traditional Software","Smart Contract"),col = c("blue","red"), ylab ="Value" )
dev.off()          
